package common

// Exemption ...
type Exemption string

const (
	// LowValue ...
	LowValue Exemption = "low_value"
	// LowRisk ...
	LowRisk Exemption = "low_risk"
	// SecureCorporatePayment ...
	SecureCorporatePayment Exemption = "secure_corporate_payment"
	// ThreeDSOutage ...
	ThreeDSOutage Exemption = "3ds_outage"
	// TrustedListing ...
	TrustedListing Exemption = "trusted_listing"
	// SCADelegation ...
	SCADelegation Exemption = "sca_delegation"
	// TransactionRiskAssessment ...
	TransactionRiskAssessment Exemption = "transaction_risk_assessment"
)

func (c Exemption) String() string {
	return string(c)
}
