package common

// Source ...
type Source string

const (
	// Number ...
	Number Source = "{{source.number}}"
	// ExpiryMonth ...
	ExpiryMonth Source = "{{source.expiry_month}}"
	// ExpiryYear ...
	ExpiryYear Source = "{{source.expiry_year}}"
	// Name ...
	Name Source = "{{source.name}}"
)
